apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: node:18-slim
        name: result
        env:
        - name: OPTION_A
          value: "FSD"
        - name: OPTION_B
          value: "AIML"
        command: ["/bin/sh", "-c"]
        args:
          - |
            apt-get update && apt-get install -y git curl
            git clone https://github.com/jaideepsingh123/agro-app-11.git /app
            cd /app/result
            npm install
            npm start
        ports:
        - containerPort: 80
          name: result
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
