apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
  namespace: voting-app
spec:
  type: ClusterIP
  ports:
  - name: "result-service"
    port: 5001
    targetPort: 5001
  selector:
    app: result
