apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: python:3.9-slim
        name: vote
        env:
        - name: OPTION_A
          value: "FSD"
        - name: OPTION_B
          value: "AIML"
        command: ["/bin/sh", "-c"]
        args:
          - |
            apt-get update && apt-get install -y git curl
            git clone https://github.com/jaideepsingh123/agro-app-11.git /app
            cd /app/vote
            pip install -r requirements.txt
            FLASK_APP=app.py FLASK_ENV=production python app.py --host=0.0.0.0 --port=5000
        ports:
        - containerPort: 5000
          name: vote
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
