apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: voting-app
spec:
  type: ClusterIP
  ports:
  - name: "vote-service"
    port: 5000
    targetPort: 5000
  selector:
    app: vote
  
