apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: mcr.microsoft.com/dotnet/sdk:7.0
        name: worker
        command: ["/bin/sh", "-c"]
        args:
          - |
            apt-get update && apt-get install -y git
            git clone https://github.com/jaideepsingh123/agro-app-11.git /app
            cd /app/worker
            dotnet restore
            dotnet run
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
